/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as ApiPublicMediaProxyRouteImport } from './routes/api/public/media-proxy'
import { Route as ApiPublicProcessVideoUrlRouteImport } from './routes/api/public/process-video-url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaProxyRoute = ApiPublicMediaProxyRouteImport.update({
  id: '/api/public/media-proxy',
  path: '/api/public/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessVideoUrlRoute =
  ApiPublicProcessVideoUrlRouteImport.update({
    id: '/api/public/process-video-url',
    path: '/api/public/process-video-url',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/library': typeof LibraryRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/process-video-url': typeof ApiPublicProcessVideoUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/library': typeof LibraryRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/process-video-url': typeof ApiPublicProcessVideoUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/library': typeof LibraryRoute
  '/studio': typeof StudioRoute
  '/trending': typeof TrendingRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/process-video-url': typeof ApiPublicProcessVideoUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/library'
    | '/studio'
    | '/trending'
    | '/api/public/media-proxy'
    | '/api/public/process-video-url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/library'
    | '/studio'
    | '/trending'
    | '/api/public/media-proxy'
    | '/api/public/process-video-url'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/library'
    | '/studio'
    | '/trending'
    | '/api/public/media-proxy'
    | '/api/public/process-video-url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LibraryRoute: typeof LibraryRoute
  StudioRoute: typeof StudioRoute
  TrendingRoute: typeof TrendingRoute
  ApiPublicMediaProxyRoute: typeof ApiPublicMediaProxyRoute
  ApiPublicProcessVideoUrlRoute: typeof ApiPublicProcessVideoUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-proxy': {
      id: '/api/public/media-proxy'
      path: '/api/public/media-proxy'
      fullPath: '/api/public/media-proxy'
      preLoaderRoute: typeof ApiPublicMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-video-url': {
      id: '/api/public/process-video-url'
      path: '/api/public/process-video-url'
      fullPath: '/api/public/process-video-url'
      preLoaderRoute: typeof ApiPublicProcessVideoUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LibraryRoute: LibraryRoute,
  StudioRoute: StudioRoute,
  TrendingRoute: TrendingRoute,
  ApiPublicMediaProxyRoute: ApiPublicMediaProxyRoute,
  ApiPublicProcessVideoUrlRoute: ApiPublicProcessVideoUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
